### ISSUE TITLE
Scrum 

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/USTH-SE-2019#113]
## Apply Scrum to your group project

1. Assign roles for members in your group. One person can play several roles.
2. Creat Product Backlog for your project by creating issues with label: product-backlog in the repo of your group leader.
3. Groups discuss and create  Sprint Backlog #1 for the next two weeks and create issues with label:sprint-backlog in your group repo.
4. Use milestones of Github to manage Sprints. (https://github.com/jvandemo/github-scrum-workflow)

## Executing Sprint #1
In the next two weeks, members get tasks from Sprint Backlog #1 using assignees of Github and update the issues while working, close them when they are done.

**Comment by linhhonblade** [comment]
Dear teacher, why we need to create issues with label: sprint-backlog? I mean we can add label: sprint-backlog to issue with label: product-backlog so there is no need to duplicate an issue. Can we do like that?

**Comment by truonganhhoang** [comment]
- sprint backlog items are breakdown of product backlog items, they are not the same. 
- sprint backlog items can have several smaller tasks, use [Task list](https://help.github.com/en/articles/about-task-lists) for managing these tasks.
